### ISSUE TITLE
Unread email counter is invalid

### ISSUE THREAD

**Issue by anton-petrunin** [tutao/tutanota#1267]
**Bug in web app**

**Describe the bug**

Spam folder is empty, but the icon says there is 1 new message, see the screenshot.

**To Reproduce**

I do not know how to reproduce the behavior

**Expected behavior**

it should be nothing next to Spam folder on the left

**Screenshots**

![Screenshot_20190512_150503](https://user-images.githubusercontent.com/8867696/57586676-61d25900-74c7-11e9-8923-f307ce52940e.png)

**Desktop (please complete the following information):**

 mozilla 66.0.4 (64-bit)

**Additional context**

**Comment by charlag** [comment]
Hi, thanks for reporting.
Please send an email to support or to the hello@tutao.de so that they can execute counting for your mailbox.

**Comment by anton-petrunin** [comment]
I did

**Comment by armhub** [comment]
Closing this issue because it should be solved by our support.

**Comment by guoyunhe** [comment]
I also have this issue... But shouldn't it be a valid bug? This shouldn't happen and need a fix.

**Comment by charlag** [comment]
@guoyunhe it shouldn't happen but it's not clear exactly if it's a bug or delayed/lost write of counter or anything else. It doesn't seem to be a bug in the client at least.

**Comment by charlag** [comment]
Yes, it makes sense, we will open it so people can see that there's a problem

**Comment by guoyunhe** [comment]
I contacted hello@tutanota.com and they said they reset the counter. But in my mailboxes, the counter is still wrong.

**Comment by l0f4r0** [comment]
I have this issue frequently.
Logout then login again, or browser switch, don't resolve it. I need to write to Tutanota support team to reset my counters.

I've noticed that reading emails while server is answering timeout can create the counter discrepancy.
Indeed, the user is not disconnected when popup "Server too long to answer" appears. Then (s)he can still read some emails which are not taken into account by the counter systematically.

But it's probably not the unique scenario/reason...

**Comment by charlag** [comment]
@guoyunhe there are multiple things which can be applied. Please write again.
@l0f4r0 please don't mix temporary miscounting (on the client) with permanent one (on the server)

We know about the problem and we hear about it a lot, we have couple of ideas on how to solve/ease it. Thanks for the patience.

**Comment by l0f4r0** [comment]
> @l0f4r0 please don't mix temporary miscounting (on the client) with permanent one (on the server)

I don't want to "mix" anything but Bernd told me to post new information here about the issue to help

**Comment by armhub** [comment]
If you see a wrong unread mail counter in one of your mail folders, please scroll that mail list down to the last mail. The counter will automatically be fixed then. If you can't scroll though all of them because you have too many emails in that folder, please write to our support and we will fix it for you.

**Comment by rgb-one** [comment]
What causes this problem?

**Comment by armhub** [comment]
For technical reasons, the unread mail counter is maintained separately from the actual state of the emails. Counter updates may get lost in case of database request timeouts. This is a technical limitation currently and we are looking into how to solve this. The automatic counter correction we implemented is our workaround for now.

**Comment by stelord** [comment]
> If you see a wrong unread mail counter in one of your mail folders, please scroll that mail list down to the last mail. The counter will automatically be fixed then. If you can't scroll though all of them because you have too many emails in that folder, please write to our support and we will fix it for you.

I wish they would....  I have raised this issue at least four times and they only tell me to scroll through the list of thousands of emails.
