### ISSUE TITLE
Support TLS-RPT

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1836]

**Comment by bedhub** [comment]
fixed with #461

**Comment by zack-95** [comment]
Hi @bedhub ,
Does closing this issue mean you now send TLS-RPT reports to MTA's of incoming email?

**Comment by charlag** [comment]
We don't send out reports yet but we declared that we want to receive them

**Comment by zack-95** [comment]
Thanks @charlag, then this issue is not fixed. TLS-RPT (RFC8460) specifically refers to the report sending. If you want to declare you receive them, then that's MTA-STS (RFC8461). Two different protocols, with two different RFCs. 

PS: I suggest you reopen this issue, since TLS-RPT is not supported yet.

**Comment by mpfau** [comment]
This issue was not about reporting. We will implement that at a later point in time.
