### ISSUE TITLE
[Android] Tuta Calendar widget doesn't load any events

### ISSUE THREAD

**Issue by daomah** [tutao/tutanota#9560]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
After adding the Tuta Calendar widget to my homescreen no events load. I just get a spinning loading animation for that never ends.

**To Reproduce**
1. Add Tuta Calendar widget
2. Select credentials
3. Select calendars
4. See spinning widget

**Expected behavior**
List of calendar events

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android 16
 - Version: [[Calendar] 304.250825.0 (Android)](https://github.com/tutao/tutanota/releases/tag/tuta-calendar-android-release-304.250825.0)

**Additional context**
I am running GrapheneOS without any Google services

---

### Context
Widgets with a big number of calendar has the tendency to stay in a load state for longer.
- This is also impacted by the user connection and size of the calendar (number of events).

#### Possible scenarios
- [ ] User has a calendar with too many events
- [ ] User was offline for too long
- [x] When opening the app and minimizing it before it finished loading, the widget can enter a infinite "loading state"
- [x] Big number of repeating events or enough old events to slow down event generation
- [x] Setting up the widget too fast(< 45 secs) for the first time **might** create a temporarily infinite loading state until the user opens the app or waits for the widget to load

We should look into it and improve loading times and user experience.

**Comment by murilopereirame** [comment]
Hi @daomah , thanks for the report! We're aware of the widget loading issues and are already working on a fix. Stay tuned for upcoming releases, they contain potential fixes for this issue

**Comment by jan1577** [comment]
Any update on this? I have the same issue

**Comment by mdstuartX** [comment]
I am a recent convert to Tutanota and cannot use the Android widget at all; all it does is spin (I let it continue overnight). I notice that the OP is on a Pixel, as am I.

Pixel 6a
Android 16
Calendar version v315.251125.0

**Comment by finedust** [comment]
Same here on Pixel 9a, v319.260107.1

The widget starts working for a while if I open the app (for say 3s at least), then after some time (and perhaps lock screen) stops again, so I guess it could have something to do with encryption?

**Comment by jcmuel** [comment]
The idea ["Calendar Integration with Android API"](https://github.com/tutao/tutanota/discussions/9977) is related to this issue, because it would allow the users to use their favorite Calendar app or widget on Android, like e.g. Etar.

**Comment by ToughDBlue** [comment]
I have a Pixel 7 with GrapheneOS and have the same issue. I don't think it's caused by too many events because it started before I hardly had any calendar events entered. I have just two calendars, personal and family, and the personal one I don't really use. I agree having the calendar integrate with the Android API is the beat solution.

**Comment by u1traviolet** [comment]
Same thing happens on my Samsung S24 FE

**Comment by Markoise** [comment]
Same on Nothing Phone 3.

It was working fine at first. I get the feeling that the widget has stopped working since I subscribed to external calendars, even though I don’t have any subscribed calendars displayed there.

A solution would be really great, as otherwise this lovely and practical widget makes absolutely no sense.

**Comment by andrehgdias** [comment]
> Same on Nothing Phone 3.
> 
> It was working fine at first. I get the feeling that the widget has stopped working since I subscribed to external calendars, even though I don’t have any subscribed calendars displayed there.
> 
> A solution would be really great, as otherwise this lovely and practical widget makes absolutely no sense.

Hello and thank you all for keeping it active, we are aware of this issue, and are constantly look out for improvements on it.
Unfortunately, this issue is very hard to reproduce what makes everything a bit harder to work on.
On version [340.260326.1](https://github.com/tutao/tutanota/milestone/423?closed=1) we fixed an [issue](https://github.com/tutao/tutanota/issues/10391) that was causing infinite loading.
If this is still happening we have a few hypothesis...

For example, do you often go offline? Turn your data off, lose connection, airplane mode, turn your device off, etc...?

**Comment by Markoise** [comment]
> For example, do you often go offline? Turn your data off, lose connection, airplane mode, turn your device off, etc...?

No, nothing of the sort. It can happen that the connection switches between mobile data and Wi-Fi.

**Comment by finedust** [comment]
> For example, do you often go offline? Turn your data off, lose connection, airplane mode, turn your device off, etc...?

I do switch off data and wifi when I'm not using the phone, so that could be. Perhaps the app might also be impacted by Android's power managing policies.

**Comment by ToughDBlue** [comment]
> Hello and thank you all for keeping it active, we are aware of this issue, and are constantly look out for improvements on it. Unfortunately, this issue is very hard to reproduce what makes everything a bit harder to work on. On version [340.260326.1](https://github.com/tutao/tutanota/milestone/423?closed=1) we fixed an [issue](https://github.com/tutao/tutanota/issues/10391) that was causing infinite loading. If this is still happening we have a few hypothesis...
> 
> For example, do you often go offline? Turn your data off, lose connection, airplane mode, turn your device off, etc...?

I still have this issue on my Pixel 7 GOS phone even running the latest Tuta mail and calendar apps. It happens quite consistently. Easily reproducible. I do not often go offline, nor turn off data, nor lose connection, nor use airplane mode much at all, and I don't often turn off or restart my phone. I'm about to just remove the calendar widget because there's no point to it if I keep having to open the app to look at my calendar.

**Comment by Markoise** [comment]
Things were fine before I subscribed to other calendars. After that, they weren't.

**Comment by Tellervo89** [comment]
Experiencing the same problem on Graphene OS (Pixel 8). unsubscribed from all external calendars to check if this would help, unfortunately it did not. It shows the calendar events maybe 10-20 % of the time, for the rest it looks like the screenshot below. WiFi or mobile data is almost always on.

<img width="670" height="810" alt="Image" src="https://github.com/user-attachments/assets/7577d72f-0cec-4927-bde1-4b1b3d7cbbd0" />

**Comment by bedhub** [comment]
Seems to also happen after restart the device: https://old.reddit.com/r/tutanota/comments/1uezbne/amdroid_widget_slow_ti_oload/

Right now we download all calendars and events when synchronizing the widget. This can take a significant amount of time. To improve we should check if the calendar has changed since last synchronization.

**Comment by andrehgdias** [comment]
From what I can remember, the loading show up when the widget view model is empty right after initialization.
If anything goes wrong with this routine the data is never populated and the widget appears as loading indefenitely.
We should look into keeping the Widget View Model alive so we don't lose the cached state, or better improve state handling and understand better its life cycle.

**Comment by t0maz** [comment]
Same issue here with calendar app v353.260630.0 on Android as well as on iOS.
It works fine if I add almost empty calendar but when I'm adding shared calendar with lots of recurring indefinitely events (imported) the widget seems to also loads indefinitely making it unusable :(
On Android it also cause the Calendar app to stop responding.

**Comment by dj-sf** [comment]
Hi @ToughDBlue and thanks for taking the time to share details about this bug with us.  We are trying to reproduce the bug on our test devices but have not been able to.  You mentioned it was easy to reproduce on your end.  Would you be able to share the exact actions you are taking when the bug occurs?

**Comment by dj-sf** [comment]
Collecting some reports of widget issues from Reddit here for reference:

https://www.reddit.com/r/tutanota/comments/1p1zxli/calendar_widget_on_android_often_stuck_loading/
https://www.reddit.com/r/tutanota/comments/1nabpyg/android_calendar_widget_broken/?chainedPosts=t3_1p1zxli

**Comment by dj-sf** [comment]
a user sent a support email on 3.8.2026 and reported that they are having this same issue, but restarting their phone temporarily fixes it.  However the behavior returns some time later.

**Comment by ToughDBlue** [comment]
> Hi [@ToughDBlue](https://github.com/ToughDBlue) and thanks for taking the time to share details about this bug with us. We are trying to reproduce the bug on our test devices but have not been able to. You mentioned it was easy to reproduce on your end. Would you be able to share the exact actions you are taking when the bug occurs?

The exact steps are to just add the calendar widget. I didn't do anything special. Around 90% of the time it will not load.

**Comment by dj-sf** [comment]
Thanks @ToughDBlue.  If it's not too sensitive, would you be willing to send the contents of the ICS file to [hello@tutao.de](mailto:hello@tutao.de) so we can try to see if there is something specific about your calendar that is causing it to happen more often?  

If you are a paying customer you can send it to us by clicking on the "?" icon in the bottom left corner of the mail client and choosing "Support". You will then be prompted to select a term related to the issue and if no FAQ entries answer your question you can click the "Other" button. This will open a form where you can send an email to our Helpdesk mailbox and attach files to the email.  In this case please attach the ics file.

In either case please include "ToughDBlue-9560" in the email so we can find it quickly.  If you choose to contact us via the hello@tutao.de email, please include it in the subject line.

**Comment by Corsico** [comment]
can confirm this still happens; 
In my case, the events load, but after a while I get logged out, so the events are replaced by a spinner until I head into the app to log in. 
The simple fix is to replace the infinite spinner with a button that triggers login. Shouldn't be too complicated to do that I don't think.

**Comment by andrehgdias** [comment]
> can confirm this still happens; In my case, the events load, but after a while I get logged out, so the events are replaced by a spinner until I head into the app to log in. The simple fix is to replace the infinite spinner with a button that triggers login. Shouldn't be too complicated to do that I don't think.

Hey, thank you  for commenting.
When you say "I get logged out", do you mean the widget simply shows the spinner, or when you open the app you have to input your account again?

Also, do you notice when exact does it happen? If it is after a long time in a offline state, or after a long period without using your phone... Any usage detail happens since we are not able to reliably reproduce it.

**Comment by Marzan0** [comment]
Chiming in to say this also is happening on my device - Pixel 9 Pro - Graphene OS. Tuta Calendar downloaded from F-Droid (Droid-ify).
Tuta Calendar is setup for Unrestricted battery usage, so it stays on in background.  

Mirroring what @Corsico said. Loading spinner doesn't stop till I open the app and it logs in / goes online. If I turn off phone screen and back on the widget still is working. It seems to occur when screen is off for a longer period of time, and it happens a lot - almost consistently. It's annoying as every time this happens I need to enter the app and let it re-sync. 

> When you say "I get logged out", do you mean the widget simply shows the spinner, or when you open the app you have to input your account again? 

To answer myself, it appears so, as whenever I open the app when the spinner is not stopping, it shows the logging in animation, as well as the offline to online sync loading bar. 

Additionally I was testing if turning off internet, or turning vpn on and off effects it. I did get a loading icon but only for a second, so seems to be working in this regard. 

EDIT:
More context. I imported events from the last calendar I was using. I don't think I have an unusual amount of event beyond what would be normal. I do have some recurring events that go back a few years.
